//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRAutos_App.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CrAutosDBEntities : DbContext
    {
        public CrAutosDBEntities()
            : base("name=CrAutosDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBCondicionVehiculo> TBCondicionVehiculo { get; set; }
        public virtual DbSet<TBDetalleVehiculo> TBDetalleVehiculo { get; set; }
        public virtual DbSet<TBEstatusPublicacion> TBEstatusPublicacion { get; set; }
        public virtual DbSet<TBExtra> TBExtra { get; set; }
        public virtual DbSet<TBExtrasVehiculo> TBExtrasVehiculo { get; set; }
        public virtual DbSet<TBFotos> TBFotos { get; set; }
        public virtual DbSet<TBMarca> TBMarca { get; set; }
        public virtual DbSet<TBPublicaciones> TBPublicaciones { get; set; }
        public virtual DbSet<TBTipoVendedor> TBTipoVendedor { get; set; }
        public virtual DbSet<TBUsuario> TBUsuario { get; set; }
        public virtual DbSet<TBVehiculo> TBVehiculo { get; set; }
        public virtual DbSet<TBVendedor> TBVendedor { get; set; }
    }
}
