//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRAutos_App.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CrAutosDBEntities : DbContext
    {
        public CrAutosDBEntities()
            : base("name=CrAutosDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBCondicionVehiculo> TBCondicionVehiculo { get; set; }
        public virtual DbSet<TBEstatusPublicacion> TBEstatusPublicacion { get; set; }
        public virtual DbSet<TBExtra> TBExtra { get; set; }
        public virtual DbSet<TBExtrasVehiculo> TBExtrasVehiculo { get; set; }
        public virtual DbSet<TBFotos> TBFotos { get; set; }
        public virtual DbSet<TBMarca> TBMarca { get; set; }
        public virtual DbSet<TBModelo> TBModelo { get; set; }
        public virtual DbSet<TBPublicaciones> TBPublicaciones { get; set; }
        public virtual DbSet<TBTipoVendedor> TBTipoVendedor { get; set; }
        public virtual DbSet<TBUsuario> TBUsuario { get; set; }
        public virtual DbSet<TBVehiculo> TBVehiculo { get; set; }
        public virtual DbSet<TBVendedor> TBVendedor { get; set; }
    }
}
