//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRAutos_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBExtra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBExtra()
        {
            this.TBExtrasVehiculo = new HashSet<TBExtrasVehiculo>();
        }
    
        public long IDExtra { get; set; }
        public string NombreExtra { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBExtrasVehiculo> TBExtrasVehiculo { get; set; }
    }
}
