//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRAutos_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBExtrasVehiculo
    {
        public long IDExtraVehiculo { get; set; }
        public long IDVehiculo { get; set; }
        public long IDExtra { get; set; }
    
        public virtual TBExtra TBExtra { get; set; }
        public virtual TBVehiculo TBVehiculo { get; set; }
    }
}
