//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRAutos_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBFotos
    {
        public long IDFoto { get; set; }
        public string Imagen { get; set; }
        public long IDVehiculo { get; set; }
    
        public virtual TBVehiculo TBVehiculo { get; set; }
    }
}
