//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRAutos_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBFotos
    {
        public long IDFoto { get; set; }
        public string Imagen { get; set; }
        public long IDVehiculo { get; set; }
    
        public virtual TBVehiculo TBVehiculo { get; set; }
    }
}
