//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRAutos_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBModelo
    {
        public long IDModelo { get; set; }
        public string NombreModelo { get; set; }
        public long IDMarca { get; set; }
    
        public virtual TBMarca TBMarca { get; set; }
    }
}
