//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRAutos_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBUsuario
    {
        public long IDUsuario { get; set; }
        public string NombreUsuario { get; set; }
        public string Contrasenna { get; set; }
        public long IDVendedor { get; set; }
    
        public virtual TBVendedor TBVendedor { get; set; }
    }
}
