//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRAutos_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBVehiculo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBVehiculo()
        {
            this.TBDetalleVehiculo = new HashSet<TBDetalleVehiculo>();
            this.TBExtrasVehiculo = new HashSet<TBExtrasVehiculo>();
            this.TBFotos = new HashSet<TBFotos>();
            this.TBPublicaciones = new HashSet<TBPublicaciones>();
        }
    
        public long IDVehiculo { get; set; }
        public string Matricula { get; set; }
        public Nullable<long> IDMarca { get; set; }
        public string TipoModelo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBDetalleVehiculo> TBDetalleVehiculo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBExtrasVehiculo> TBExtrasVehiculo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBFotos> TBFotos { get; set; }
        public virtual TBMarca TBMarca { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBPublicaciones> TBPublicaciones { get; set; }
    }
}
