//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRAutos_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBVendedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBVendedor()
        {
            this.TBPublicaciones = new HashSet<TBPublicaciones>();
            this.TBUsuario = new HashSet<TBUsuario>();
        }
    
        public long IDVendedor { get; set; }
        public string Nombre { get; set; }
        public string Apellido1 { get; set; }
        public string Apellido2 { get; set; }
        public string Telefono { get; set; }
        public string Correo { get; set; }
        public Nullable<long> IDTipoVendedor { get; set; }
        public string Empresa { get; set; }
        public Nullable<int> Calificación { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBPublicaciones> TBPublicaciones { get; set; }
        public virtual TBTipoVendedor TBTipoVendedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBUsuario> TBUsuario { get; set; }
    }
}
